# -*- coding: utf-8 -*-
"""Ollama Prompt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12YqHVxaYpMxYA50NEZ6OIKVAIMTgnwCk
"""

# Aggressively uninstall all opentelemetry and related packages first
!pip uninstall -y opentelemetry-api opentelemetry-sdk opentelemetry-proto opentelemetry-exporter-otlp-proto-common opentelemetry-exporter-otlp-proto-grpc opentelemetry-exporter-otlp-proto-http opentelemetry-exporter-otlp-proto-json opentelemetry-semantic-conventions google-adk opentelemetry-exporter-gcp-logging

# Install chromadb first, allowing it to pull its preferred opentelemetry versions
!pip install -q chromadb

# Install all other required Python packages
!pip install -q fastapi uvicorn pyngrok nest_asyncio ollama pydantic sentence-transformers

# Install zstd for system-level dependency (if needed by chromadb or others)
!sudo apt-get install -y zstd

!pip install -q ollama
import subprocess
import time
import ollama

# Install Ollama if not already installed
# This command downloads and runs the Ollama installation script.
# The 'sh' command is used to execute the script.
# The output of this installation will not be captured by subprocess.run unless explicitly handled.
# We assume it runs successfully as a prerequisite for the next step.
install_ollama_command = "curl -fsSL https://ollama.com/install.sh | sh"
subprocess.run(install_ollama_command, shell=True, check=True)

# Start the Ollama daemon in the background
print("Starting Ollama server...")
ollama_process = subprocess.Popen(
    ['ollama', 'serve'],
    stdout=subprocess.PIPE,
    stderr=subprocess.PIPE
)

# Wait for Ollama server to be ready
# This loop will continuously try to connect to the Ollama server
# until it becomes available or a timeout occurs.
max_retries = 20
for i in range(max_retries):
    try:
        # Attempt to list models to check if the server is responsive
        ollama.Client(host='http://localhost:11434').list()
        print(f"Ollama server is ready after {i+1} retries.")
        break
    except ollama.ResponseError as e:
        print(f"Ollama server not ready yet (attempt {i+1}/{max_retries}): {e}")
        time.sleep(2) # Wait for 2 seconds before retrying
    except Exception as e:
        print(f"An unexpected error occurred while waiting for Ollama (attempt {i+1}/{max_retries}): {e}")
        time.sleep(2)
else:
    print("Failed to connect to Ollama server after multiple retries. Please check the server logs.")
    raise ConnectionError("Ollama server did not start correctly.")

# Now that the server is running, pull the model
print("Pulling Llama3.2:3B model...")
!ollama pull llama3.2:3b

print("You may now start using Ollama.")

import json
import ollama
import traceback
from typing import List, Dict
from fastapi import FastAPI, HTTPException, Depends
from sentence_transformers import SentenceTransformer
from pydantic import BaseModel # Added this import

# ── 1. The Mapping Logic (The Dependency) ──────────────────────────────────

class KeywordMapper:
    def __init__(self):
        # In a real app, you'd load this from a .json file:
        # with open('mapping.json', 'r') as f: self.raw_map = json.load(f)
        self.raw_map = {
            "pet-friendly": ["pet-friendly", "accept animal de companie", "animal de companie", "animale de companie", "petfriendly"],
            "parcare": ["loc de parcare inclus", "garaj", "parcare in apropiere", "loc de parcare", "parcare subterana"],
            "gradina": ["curte", "gradina"],
            "metrou": ["metrou", "metro"],
            "centrala": ["centrala", "centrala propie"],
            "renovat": ["nou", "renovat", "utilat", "mobilat", "mobilat/utilat"]
        }
        # Flatten the map for O(1) lookup: {'garaj': 'parcare', 'metro': 'metrou', ...}
        self.lookup = {}
        for main_cat, variations in self.raw_map.items():
            for v in variations:
                self.lookup[v.lower()] = main_cat

    def normalize(self, extracted_keywords: List[str]) -> List[str]:
        normalized = set()
        for kw in extracted_keywords:
            kw_lower = kw.lower().strip()

            # 1. Check for exact match
            if kw_lower in self.lookup:
                normalized.add(self.lookup[kw_lower])
                continue

            # 2. Check if the extracted keyword CONTAINS or IS CONTAINED in our synonyms
            # This catches "loc de parcare" if your dict has "parcare"
            for variation, main_cat in self.lookup.items():
                if variation in kw_lower or kw_lower in variation:
                    normalized.add(main_cat)
                    break
        return list(normalized)

# Initialize the mapper once (Singleton pattern)
mapper_instance = KeywordMapper()

def get_mapper():
    """FastAPI Dependency provider."""
    return mapper_instance

# ── 2. Pydantic Schemas ──────────────────────────────────────────────────────

class UserQuery(BaseModel):
    text: str

class VibeSearch(BaseModel):
    hard_filters: List[str]  # These will be mapped to your dict
    soft_filters: List[str]  # These will be used for Vector Search later

# ── 3. FastAPI Application ───────────────────────────────────────────────────

app = FastAPI(title="Real Estate AI Agent")

@app.post("/process-search")
async def process_search(
    query: UserQuery,
    mapper: KeywordMapper = Depends(get_mapper)
):
    try:
        # Step A: Extract using Ollama
        system_prompt = f"""
        You are a real estate agent. Extract features from the user prompt.
        Known categories: {list(mapper.raw_map.keys())}.
        Put recognized categories or synonyms in 'hard_filters'.
        Put subjective vibes (sunny, cozy, spacious) in 'soft_filters'.
        If you see a feature that matches name (e.g., 'parcare') instead of the raw text.
        Output JSON.
        """

        response = ollama.chat(
            model='llama3.2:3b',
            messages=[
                {'role': 'system', 'content': system_prompt},
                {'role': 'user', 'content': query.text},
            ],
            format=VibeSearch.model_json_schema(),
            options={'temperature': 0}
        )

        raw_output = json.loads(response['message']['content'])

        # Step B: Use the Dependency to normalize Hard Filters
        # This ensures "garaj" becomes "parcare"
        final_hard_filters = mapper.normalize(raw_output.get("hard_filters", []))

        # Step C: Build the final response
        # We'll also build the URL fragment for you
        url_fragment = "-".join(final_hard_filters)
        search_url = f"https://somerealestatewebsite.com/city/q-{url_fragment}/allListings"

        return {
            "original_query": query.text,
            "url_filters": final_hard_filters,
            "vibe_terms": raw_output.get("soft_filters", []),
            "generated_url": search_url
        }

    except Exception as e:
        print(traceback.format_exc())
        raise HTTPException(status_code=500, detail=str(e))

import chromadb
from pydantic import BaseModel
import traceback
from fastapi import HTTPException
from typing import List, Optional

model = SentenceTransformer('paraphrase-multilingual-MiniLM-L12-v2')

# Define ChromaDB path and initialize client/collection
CHROMA_DB_PATH = "/content/drive/MyDrive/Real estate parser/my_local_db/"
client = chromadb.PersistentClient(path=CHROMA_DB_PATH)
collection_name = "listings"
try:
    collection = client.get_or_create_collection(name=collection_name)
    print(f"ChromaDB collection '{collection_name}' ready at {CHROMA_DB_PATH}")
except Exception as e:
    print(f"Error initializing ChromaDB collection: {e}")

# --- Pydantic Models ---

class ListingData(BaseModel):
    description: str
    url: str
    hard_filters: List[str] # From /process-search logic
    soft_filters: List[str] # From /process-search logic

class EmbeddingRequest(BaseModel):
    listings: List[ListingData]

class SearchQuery(BaseModel):
    vibe_terms: List[str]
    url_filters: List[str]
    limit: int = 5

# --- Endpoints ---

@app.post("/embed")
async def store_listings(data: EmbeddingRequest):
    try:
        descriptions = [l.description for l in data.listings]
        urls = [l.url for l in data.listings]
        embeddings_list = model.encode(descriptions).tolist()

        # Create metadata including filters for filtering later
        metadatas = []
        for l in data.listings:
            meta = {"url": l.url}
            # ChromaDB 'where' filters work best with simple types or 'in' logic
            # We'll store filters as a JSON string or individual flags if preferred
            # For simplicity, we flag the presence of hard filters
            for hf in l.hard_filters:
                meta[f"filter_{hf.lower()}"] = True
            metadatas.append(meta)

        collection.upsert(
            documents=descriptions,
            embeddings=embeddings_list,
            metadatas=metadatas,
            ids=urls
        )

        return {"message": f"Stored {len(urls)} listings successfully."}

    except Exception as e:
        print(traceback.format_exc())
        raise HTTPException(status_code=500, detail=str(e))

@app.post("/search-listings")
async def search_listings(query: SearchQuery):
    try:
        # 1. Encode the vibe terms (soft filters) into a single search vector
        search_text = " ".join(query.vibe_terms)
        query_embedding = model.encode([search_text]).tolist()[0]

        # 2. Build the 'where' filter for hard requirements
        # This ensures the results MUST match the extracted features
        where_clause = {}
        if query.url_filters:
            if len(query.url_filters) == 1:
                where_clause = {f"filter_{query.url_filters[0].lower()}": True}
            else:
                where_clause = {"$and": [{f"filter_{f.lower()}": True} for f in query.url_filters]}

        # 3. Query ChromaDB
        results = collection.query(
            query_embeddings=[query_embedding],
            n_results=query.limit,
            where=where_clause if where_clause else None
        )

        # 4. Format Results
        formatted_results = []
        for i in range(len(results['ids'][0])):
            formatted_results.append({
                "url": results['ids'][0][i],
                "description": results['documents'][0][i],
                "distance": results['distances'][0][i],
                "metadata": results['metadatas'][0][i]
            })

        return {
            "query_vibe": search_text,
            "matches": formatted_results
        }

    except Exception as e:
        print(traceback.format_exc())
        raise HTTPException(status_code=500, detail=str(e))

import asyncio
import nest_asyncio
import uvicorn
from pyngrok import ngrok
from google.colab import userdata

# ── ngrok authentication ──────────────────────────────────────────────────────
# Get a free token at https://dashboard.ngrok.com/
ngrok_token = userdata.get('ngrokToken')
ngrok.set_auth_token(ngrok_token)

# Open a tunnel to port 8000
tunnel = ngrok.connect(8000)
PUBLIC_URL = tunnel.public_url
print(f"\n{'='*60}")
print(f"  PUBLIC URL : {PUBLIC_URL}")
print(f"  ENDPOINT   : {PUBLIC_URL}/process-search")
print(f"{'='*60}\n")

# ── Start Uvicorn inside the existing Colab event loop ───────────────────────
nest_asyncio.apply()

config = uvicorn.Config(app, host="0.0.0.0", port=8000, loop="asyncio")
server = uvicorn.Server(config)

loop = asyncio.get_event_loop()
loop.create_task(server.serve())

print("Server is running. Keep this cell alive (it will not block).")
print("Send POST requests to the endpoint printed above.")

